Add some iscsi work

diff --git a/group_vars/all b/group_vars/all
--- a/group_vars/all
+++ b/group_vars/all
@@ -28,6 +28,52 @@ sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
 sshkey2: "{{ lookup('file', '~/.ssh/id_ansible.pub', errors='ignore') | default('') }}"
 pullsecret: "{{ lookup('file', '~/.pullsecret.json') }}"
 kubeadmin_pass: "{{ lookup('file', '~/.kubeadminpass') }}"
+iscsi_mco_pool: "worker"
+iscsi_target_ip: 192.168.66.100
+iscsi_iqn: iqn.2024-02.com.example
+iscsi_login_script: |
+  #!/bin/bash
+  TARGET_IP={{ iscsi_target_ip }}
+  TARGET_IQN={{ iscsi_iqn }}
+  check_target() {
+  ACTIVE_SESSIONS=$(iscsiadm -m session 2>&1)
+  if [[ 0$(echo ${ACTIVE_SESSIONS} | grep -c "${TARGET_IQN}") -ge 01 ]]
+  then
+    echo "Target found"
+    return 0
+  else
+    echo "Target not found"
+    return 1
+  fi
+  }
+  main(){
+    check_target
+    TARGET_FOUND=$?
+    if [[ 0${TARGET_FOUND} -eq 00 ]]
+    then
+      echo "iSCSI already configured"
+      exit 0
+    else
+      echo "iSCSI not configured, configuring"
+      iscsiadm -m discovery -t st -p ${TARGET_IP}
+      sleep 3
+      iscsiadm --mode  node --target ${TARGET_IQN} --portal ${TARGET_IP} -l
+      sleep 3
+      check_target
+      TARGET_FOUND=$?
+      if [[ 0${TARGET_FOUND} -eq 00 ]]
+      then
+        echo "iSCSI configured correctly"
+        exit 0
+      else
+        echo "Failed to configure iSCSI"
+        exit 1
+      fi
+    fi
+  }
+  main
+  exit $?
+
 bridge_interface: "br0"
 ca_folder: "/tmp/sno-ca"
 firefox_profile: "/home/michele/.mozilla/firefox/1u0ue9rm.OpenShift-1708184658172"
diff --git a/playbooks/full-cluster.yml b/playbooks/full-cluster.yml
--- a/playbooks/full-cluster.yml
+++ b/playbooks/full-cluster.yml
@@ -277,51 +277,71 @@
       args:
         chdir: "{{ fullclusterfolder }}"
 
-    - name: Apply mirroring yaml files
-      ansible.builtin.shell: |
-        set -e -o pipefail
-        export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
-        "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ local_mirror }}/workspace/working-dir/cluster-resources/*oc-mirror.yaml"
-        "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ local_mirror }}/workspace/working-dir/cluster-resources/cs-*index*v{{ ocp_maj_min_version_dashed }}.yaml"
-      when: enable_disconnected
-      register: mirroring
-      until: mirroring is not failed
-      retries: 50
-      delay: 30
+    # - name: Apply mirroring yaml files
+    #   ansible.builtin.shell: |
+    #     set -e -o pipefail
+    #     export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
+    #     "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ local_mirror }}/workspace/working-dir/cluster-resources/*oc-mirror.yaml"
+    #     "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ local_mirror }}/workspace/working-dir/cluster-resources/cs-*index*v{{ ocp_maj_min_version_dashed }}.yaml"
+    #   when: enable_disconnected
+    #   register: mirroring
+    #   until: mirroring is not failed
+    #   retries: 50
+    #   delay: 30
+    #
+    # - name: Disable default catalog sources
+    #   ansible.builtin.shell: |
+    #     set -e -o pipefail
+    #     export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
+    #     "{{ mirrorfolder }}/{{ ocp_version }}"/oc patch OperatorHub cluster --type json -p '[{"op": "add", "path": "/spec/disableAllDefaultSources", "value": true}]'
+    #   when: enable_disconnected
+    #   register: catalog_sources
+    #   until: catalog_sources is not failed
+    #   retries: 50
+    #   delay: 20
 
-    - name: Disable default catalog sources
-      ansible.builtin.shell: |
-        set -e -o pipefail
-        export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
-        "{{ mirrorfolder }}/{{ ocp_version }}"/oc patch OperatorHub cluster --type json -p '[{"op": "add", "path": "/spec/disableAllDefaultSources", "value": true}]'
-      when: enable_disconnected
-      register: catalog_sources
-      until: catalog_sources is not failed
-      retries: 50
-      delay: 20
+    # - name: Template out nfs bits
+    #   tags:
+    #     - nfs
+    #   ansible.builtin.template:
+    #     src: "../templates/{{ item }}"
+    #     dest: "{{ tempfolder }}/fullcluster/{{ item }}"
+    #     mode: "0644"
+    #   with_items:
+    #     - nfs.yaml
+    #
+    # - name: Install nfs
+    #   tags:
+    #     - nfs
+    #   ansible.builtin.shell: |
+    #     set -e -o pipefail
+    #     export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
+    #     helm repo add csi-driver-nfs https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts || /bin/true
+    #     helm install csi-driver-nfs csi-driver-nfs/csi-driver-nfs --namespace kube-system --version v4.9.0
+    #     "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ tempfolder }}/fullcluster/nfs.yaml"
+    #   register: nfsstorage
+    #   until: nfsstorage is not failed
+    #   retries: 10
+    #   delay: 20
 
-    - name: Template out nfs bits
+    - name: Template out iscsi MCP for workers
       tags:
-        - nfs
+        - iscsi
       ansible.builtin.template:
-        src: "../templates/{{ item }}"
-        dest: "{{ tempfolder }}/fullcluster/{{ item }}"
+        src: "../templates/mcp-workers-iscsi.yaml"
+        dest: "{{ tempfolder }}/fullcluster/mcp-workers-iscsi.yaml"
         mode: "0644"
-      with_items:
-        - nfs.yaml
 
-    - name: Install nfs
+    - name: Install local storage operator
       tags:
-        - nfs
+        - iscsi
       ansible.builtin.shell: |
         set -e -o pipefail
         export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
-        helm repo add csi-driver-nfs https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts || /bin/true
-        helm install csi-driver-nfs csi-driver-nfs/csi-driver-nfs --namespace kube-system --version v4.9.0
-        "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ tempfolder }}/fullcluster/nfs.yaml"
-      register: nfsstorage
-      until: nfsstorage is not failed
-      retries: 10
+        "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ tempfolder }}/fullcluster/mcp-workers-iscsi.yaml"
+      register: mcg_iscsi
+      until: mcg_iscsi is not failed
+      retries: 50
       delay: 20
 
     # - name: Template out localstorage bits
