no updates

diff --git a/playbooks/full-cluster.yml b/playbooks/full-cluster.yml
--- a/playbooks/full-cluster.yml
+++ b/playbooks/full-cluster.yml
@@ -5,7 +5,7 @@
   become: true
   vars:
     all_nodes:
-    - nginx
+    # - nginx
     - bootstrap
     - master-0
     - master-1
@@ -460,13 +460,13 @@
         dest: "{{ fullclusterfolder }}/update-operator.yaml"
         mode: "0644"
 
-    - name: Install update operator
-      tags:
-        - update
-      ansible.builtin.shell: |
-        set -e
-        export KUBECONFIG="{{ fullclusterfolder }}/auth/kubeconfig"
-        {{ oc_bin }} apply -f "{{ fullclusterfolder }}/update-operator.yaml"
+    # - name: Install update operator
+    #   tags:
+    #     - update
+    #   ansible.builtin.shell: |
+    #     set -e
+    #     export KUBECONFIG="{{ fullclusterfolder }}/auth/kubeconfig"
+    #     {{ oc_bin }} apply -f "{{ fullclusterfolder }}/update-operator.yaml"
 
     - name: Reset ca folder
       ansible.builtin.shell: |
@@ -729,22 +729,22 @@
         - virt-subscription.yaml
         - virt-hyperconverged.yaml
 
-    - name: Apply update yaml file
-      tags:
-        - update
-      ansible.builtin.shell: |
-        set -e -o pipefail
-        export KUBECONFIG="{{ fullclusterfolder }}/auth/kubeconfig"
-        {{ oc_bin }} apply -n openshift-update-service -f {{ local_mirror }}/yamls/cluster-resources/updateService.yaml
-      when: enable_disconnected
-      register: mirroring
-      until: mirroring is not failed
-      retries: 40
-      delay: 10
+    # - name: Apply update yaml file
+    #   tags:
+    #     - update
+    #   ansible.builtin.shell: |
+    #     set -e -o pipefail
+    #     export KUBECONFIG="{{ fullclusterfolder }}/auth/kubeconfig"
+    #     {{ oc_bin }} apply -n openshift-update-service -f {{ local_mirror }}/yamls/cluster-resources/updateService.yaml
+    #   when: enable_disconnected
+    #   register: mirroring
+    #   until: mirroring is not failed
+    #   retries: 40
+    #   delay: 10
 
-    # - name: STOP HERE
-    #   ansible.builtin.fail:
-    #     msg: "STOP HERE FOR NOW"
+    - name: STOP HERE
+      ansible.builtin.fail:
+        msg: "STOP HERE FOR NOW"
 
     - name: Apply fusion bits
       tags:
